kind: pipeline
type: docker
name: shannengzhixiang-pay-ui


steps:
- name: docker-build
  image: plugins/docker
  settings:
    mirror: https://jnyis2wm.mirror.aliyuncs.com
    repo: repo.internal.hafuhafu.cn/hulu0811/shannengzhixiang-pay-ui
    registry: repo.internal.hafuhafu.cn
    target: build
    cache_from: repo.internal.hafuhafu.cn/hulu0811/shannengzhixiang-pay-ui:build
    tags:
      - build


- name: docker-final
  image: plugins/docker
  settings:
    mirror: https://jnyis2wm.mirror.aliyuncs.com
    repo: repo.internal.hafuhafu.cn/hulu0811/shannengzhixiang-pay-ui
    registry: repo.internal.hafuhafu.cn
    cache_from: 
      - repo.internal.hafuhafu.cn/hulu0811/shannengzhixiang-pay-ui:build
      - repo.internal.hafuhafu.cn/hulu0811/shannengzhixiang-pay-ui:latest
    tags:
      - latest
      - ${DRONE_COMMIT}

- name: dron8s-api
  image: bh90210/dron8s:latest
  settings:
    yaml: ./deploy.yaml
    image_tag: ${DRONE_COMMIT}
    kubeconfig:
        from_secret: kubeconfig